export { Login } from "./Auth/Login"
export { Register } from "./Auth/Register"
export { VerifyEmail } from "./Auth/VerifyEmail"
export { Home } from "./Home/Home"
export { Account } from "./Account/Account"
